            - name: Discord Reporter
  # You may pin to the exact commit or the version.
  # uses: TeamGalacticraft/discord-reporter@a9c55d6f9fc2245aca27367c95e9d36c6aa36359
  uses: TeamGalacticraft/discord-reporter@1.0.0
  with:
    # The Discord-provided webhook url.
    webhook: https://discord.com/api/webhooks/1398640865777422336/6PuGnEdJOeR4GsKA_rP0yFxmB1iKoV2e2LuE_ZqrB40YFIbmToxPMKEXukL6hUBdrYN4
    # Outcome of previous step, use ${{ steps.<build step>.outcome }}.
    outcome: 
    # Github token, use ${{ secrets.GITHUB_TOKEN }}.
    token: 
    # The directory containing JUnit5 TEST-*.xml files.
    tests: # optional, default is build/test-results/test/
          
